AtlasSwitch/blog/forms.py
# forms for submitting new blog posts will be here

AtlasSwitch/portfolio/forms.py
# This is for the portfolio form for writing new portfolio posts

AtlasSwitch/blog/views.py
from flask import render_template, Blueprint
from datetime import datetime


blog = Blueprint('blog', __name__)


@blog.context_processor
def inject_now():
    return {'now': datetime.utcnow()}


#@blog.route('/blog')
def blog_posts():
    return render_template('static_site/blog.html')

AtlasSwitch/core/views.py
from flask import render_template, Blueprint, request
from AtlasSwitch.models import User, History, PandS
from datetime import datetime


core = Blueprint('core', __name__)


@core.context_processor
def inject_now():
    return {'now':datetime.utcnow()}


@core.route('/')
def index():
    return render_template('static_site/index.html')


@core.route('/history')
def history():
    history = History.query.get(1)
    return render_template('static_site/history.html', history=history)


@core.route('/team')
def team():
    # This is probably going to pull from the database
    return render_template('static_site/team.html')


@core.route('/products_and_services')
def products_and_services():
    page = request.args.get('page', 1, type=int)
    pands = PandS.query.order_by(PandS.id.asc()).paginate(page=page, per_page=20)
    return render_template('static_site/pands.html', pands=pands)

AtlasSwitch/portfolio/views.py
from flask import render_template, Blueprint
from datetime import datetime


portfolio = Blueprint('portfolio', __name__)


@portfolio.context_processor
def inject_now():
    return {'now': datetime.utcnow()}


#@portfolio.route('/portfolio', methods=['GET', 'POST'])
def portfolio_page():
    return render_template('static_site/portfolio.html')

AtlasSwitch/users/views.py
from flask import render_template, Blueprint, url_for, request, redirect
from AtlasSwitch.models import User
from AtlasSwitch.users.forms import LoginForm
from flask_login import login_user, logout_user, current_user, login_required
from datetime import datetime


users = Blueprint('users', __name__)


@users.context_processor
def inject_now():
    return {'now': datetime.utcnow()}


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    error = None
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            next = request.args.get('next')
            if next is None or not next[0] == '/':
                next = url_for('employees.index')
            return redirect(next)
        else:
            error = 'Invalid email or password'
        # if a user was trying to access a page that required a log in, this will let them go to that page after log in

    return render_template('static_site/login.html', form=form, error=error)

AtlasSwitch/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title></title>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/mainpage.css')}}">

</head>
<body>
    <nav class='navbar navbar-expand-lg navbar-dark static-top navbar-fixed-top header-wrapper'>
        <div class='container'>
        <a class="navbar-brand" href="{{url_for('core.index')}}">Atlas Switch</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class='collapse navbar-collapse' id='navbarContent'>
            <ul class='navbar-nav ml-auto'>                
                <li class='nav-item dropdown'>
                    <a class="nav-link " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        About Us
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{{url_for('core.history')}}">History</a>
                      <a class="dropdown-item" href="{{url_for('core.team')}}">Meet the team</a>
                  </div>
                  <li class="nav-item">
                    <a class="nav-link" href="{{url_for('core.products_and_services')}}">Products and Services</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{url_for('portfolio.portfolio_page')}}">Portfolio</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{url_for('blog.blog_posts')}}">Blog</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{url_for('core.contact')}}">Contact Us</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.login')}}">Log in</a>
                  </li>
                </li>                
            </ul>
        </div>
     </div>
    </nav>   

{% block content %}

{% endblock %}
<div id='bottomcontact'> 
  <aside>
    <div class='container'>
      <figcaption>Atlas Switch Co., Inc.</figcaption>
      <figcaption>969 Stewart Avenue</figcaption>
      <figcaption>Garden City, NY 11530</figcaption>
    </div>
    <div>
      Phone: <a href="tel:5162226280">(516) 222-6280</a><br>
      Email: <a href="mailto:info@atlasswitch.com">info@atlasswitch.com</a></div>
  </aside>
  <div class='container text-center' id='copy'>&copy; Atlas Switch</div>
</div>
</body>
</html>

AtlasSwitch/templates/blog.html
{% extends 'base.html' %}

{% block content %}
 <div class="container static-content">
     Loop through posts in database <br>
 </div>
{% endblock %}

AtlasSwitch/templates/contact.html
{% extends 'base.html' %}

{% block content %}
<div class='container static-content'>
    Contact form
</div>
{% endblock %}

AtlasSwitch/templates/history.html
{% extends 'base.html' %}

{% block content %}
<div>
    <img width='100%' src="static/sitepics/history1.jpg">
    <div class='container static-content'>
        <p>
            Atlas Switch was founded in 1971 by John Paradise in a small warehouse in Long Island City.  After leaving Federal Pacific, where he worked as an engineer, John was committed to building high quality switchgear with the best customer service in the business.  All of these years later, Atlas Switch maintains a reputation for the fastest responsiveness and the highest quality.  After his passing in 2002, his daughter, Gina Paradise took over as the President and CEO.  During her tenure, she has begun initiatives that have led to a modernization of the company's products, technologies and workflows.  
        </p>
        
    </div>
</div>
{% endblock %}

AtlasSwitch/templates/index.html
{% extends 'base.html' %}

{% block content %}
<section id='maincontent'>
    <div class='container' id='mainheader'>
            <h1 class='indexh1'>HELPING TO DISTRIBUTE POWER <br> THROUGHOUT NEW YORK CITY</h1>
    </div>

</section>
{% endblock %}

AtlasSwitch/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div id='login-div'>
    <form id='login-form' method='POST'>
        {{form.hidden_tag()}}
        <div class='form-group'>
            <label>
                {{form.email.label()}}
            </label>
            
            {{form.email(class='form-control')}}
        </div>
        <div class='form-group'>
            {{form.password.label}}
            {{form.password(class='form-control')}}
        </div>
        <div class='form-group'>
            {{form.submit(class='btn login-btn')}}
        </div>
            
            
        
    </form>
</div>
{% endblock %}

AtlasSwitch/templates/pands.html
{% extends 'base.html' %}

{% block content %}
<div class='container static-content'>
    put in a responsive grid system with all of our products and services
</div>

{% endblock %}

AtlasSwitch/templates/portfolio.html
{% extends 'base.html' %}

{% block content %}
<div class="container static-content">
    Loop through database and display portfolio pages
</div>

{% endblock %}

AtlasSwitch/templates/team.html
{% extends 'base.html' %}

{% block content %}
<div class='container static-content'>
    probably a for loop that loops through the database and posts team member cards
</div>
{% endblock %}