AtlasSwitch/quote/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, IntegerField, TextAreaField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError, Required
import datetime


class NewQuote(FlaskForm):
    jobname = StringField('Job Name')
    jobaddress = StringField('Job Address')
    amount = IntegerField('Amount', validators=[DataRequired()])
    followdate = DateField('Follow Up Date', validators=[DataRequired()],
                           default=datetime.date.today() + datetime.timedelta(days=7))
    notes = TextAreaField('Notes')
    submit = SubmitField('Submit')

AtlasSwitch/admin/views.py
from flask import render_template, Blueprint, url_for, request, redirect, flash
from AtlasSwitch.models import User, History, PandS
from AtlasSwitch.users.forms import LoginForm
from flask_login import login_user, logout_user, current_user, login_required
from AtlasSwitch.users.roles import admin_required
from AtlasSwitch.users.forms import NewUserForm
from AtlasSwitch.admin.forms import HistoryForm, PandSForm
from AtlasSwitch import db
from AtlasSwitch.admin.picture_handler import product_pic


admin = Blueprint('admin', __name__)


@admin.route('/admin')
@login_required
@admin_required
def admin_index():
    return render_template('admin/index.html')


@admin.route('/admin/report_panel')
@login_required
@admin_required
def report_panel():
    return render_template('admin/report_panel.html')


@admin.route('/admin/user_panel')
@login_required
@admin_required
def user_panel():
    page = request.args.get('page', 1, type=int)
    users = User.query.order_by(User.id.asc()).paginate(page=page, per_page=20)
    return render_template('admin/user_panel.html', users=users)


@admin.route('/admin/create_new_user', methods=['GET', 'POST'])
@login_required
@admin_required
def create_new_user():
    form = NewUserForm()
    if form.validate_on_submit():
        new_user = User(name=form.name.data,
                        email=form.email.data.lower(),
                        access_level=form.access_level.data,
                        password=form.password.data)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('admin.user_panel'))
    return render_template('/admin/create_new_user.html', form=form)


@admin.route('/admin/<int:user_id>/delete', methods=['GET', 'POST'])
@login_required
@admin_required
def delete_user(user_id):
    user = User.query.get(user_id)
    if current_user.id != user_id:
        db.session.delete(user)
        db.session.commit()
        return redirect(url_for('admin.user_panel'))
    return redirect(url_for('admin.user_panel'))


@admin.route('/admin/portfolio_panel')
@login_required
@admin_required
def portfolio_panel():
    return render_template('admin/portfolio_panel.html')


@admin.route('/admin/blog_panel')
@login_required
@admin_required
def blog_panel():
    return render_template('admin/blog_panel.html')


@admin.route('/admin/static_panel', methods=['GET', 'POST'])
@login_required
@admin_required
def static_panel():
    history_post = History.query.get_or_404(1)
    history = HistoryForm()
    if history.submit.data and history.validate():
        history_post.text = history.text.data
        db.session.commit()
        return redirect(url_for('admin.static_panel'))

    page = request.args.get('page', 1, type=int)
    pands_post = PandS.query.order_by(PandS.id.asc()).paginate(page=page, per_page=20)
    new_pands = PandSForm()
    new_pands.submitpands.label.text = 'Create New Product or Service'

    if new_pands.submitpands.data and new_pands.validate():
        pic = product_pic(new_pands.image.data, new_pands.name.data)
        new_prod = PandS(name=new_pands.name.data,
                         description=new_pands.text.data,
                         image=pic)
        db.session.add(new_prod)
        db.session.commit()
        return redirect(url_for('admin.static_panel'))

    if request.method == 'GET':
        history.text.data = history_post.text

    return render_template('admin/static_panel.html', history=history, pands_post=pands_post,
                           new_pands=new_pands)


@admin.route('/admin/delete_pands/<int:pands_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def delete_pands(pands_id):
    pands = PandS.query.get(pands_id)
    db.session.delete(pands)
    db.session.commit()
    return redirect(url_for('admin.static_panel'))

AtlasSwitch/core/views.py
from flask import render_template, Blueprint, request
from AtlasSwitch.models import User, History, PandS
from datetime import datetime


core = Blueprint('core', __name__)


@core.context_processor
def inject_now():
    return {'now':datetime.utcnow()}


@core.route('/')
def index():
    return render_template('static_site/index.html')


@core.route('/history')
def history():
    history = History.query.get(1)
    return render_template('static_site/history.html', history=history)


@core.route('/team')
def team():
    # This is probably going to pull from the database
    return render_template('static_site/team.html')


@core.route('/products_and_services')
def products_and_services():
    page = request.args.get('page', 1, type=int)
    pands = PandS.query.order_by(PandS.id.asc()).paginate(page=page, per_page=20)
    return render_template('static_site/pands.html', pands=pands)

AtlasSwitch/employees_only/views.py
from flask import render_template, Blueprint, url_for, request, redirect
from AtlasSwitch.models import User, FollowUp
from AtlasSwitch.users.forms import LoginForm
from flask_login import login_user, logout_user, current_user, login_required
from AtlasSwitch.users.roles import admin_required, sales_required, engineer_required
from AtlasSwitch.quote.forms import NewQuote
import datetime
from AtlasSwitch import db


employees = Blueprint('employees', __name__)


@employees.route('/employees')
@login_required
def index():
    return render_template('employee_site/index.html')


@employees.route('/sales')
@login_required
@sales_required
def sales():
    return render_template('employee_site/sales.html')


@employees.route('/sales/quote', methods=['GET', 'POST'])
@login_required
@sales_required
def quote():
    newquote = NewQuote()
    if newquote.validate_on_submit():
        newquoteentry = FollowUp(salesman=current_user.name,
                                 jobname=newquote.jobname.data,
                                 job_address=newquote.jobaddress.data,
                                 amount=newquote.amount.data,
                                 date=datetime.date.today(),
                                 nextfollowup=newquote.followdate.data,
                                 notes=newquote.notes.data)
        db.session.add(newquoteentry)
        db.session.commit()
        return redirect(url_for('employees.quote'))
    return render_template('employee_site/quote.html', newquote=newquote)


@employees.route('/quote/all_quotes')
@login_required
@sales_required
def all_quotes():
    page = request.args.get('page', 1, type=int)
    quotes = FollowUp.query.order_by(FollowUp.id.desc()).paginate(page=page, per_page=100)
    return render_template('employee_site/all_quotes.html', quotes=quotes)


@employees.route('/sales/crm')
@login_required
@sales_required
def crm():
    return render_template('employee_site/crm.html')


@employees.route('/engineering')
@login_required
@engineer_required
def engineering():
    return render_template('employee_site/engineering.html')


@employees.route('/advisory_board')
@login_required
def advisory_board():
    return render_template('employee_site/advisory_board.html')

AtlasSwitch/users/views.py
from flask import render_template, Blueprint, url_for, request, redirect
from AtlasSwitch.models import User
from AtlasSwitch.users.forms import LoginForm
from flask_login import login_user, logout_user, current_user, login_required
from datetime import datetime


users = Blueprint('users', __name__)


@users.context_processor
def inject_now():
    return {'now': datetime.utcnow()}


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    error = None
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            next = request.args.get('next')
            if next is None or not next[0] == '/':
                next = url_for('employees.index')
            return redirect(next)
        else:
            error = 'Invalid email or password'
        # if a user was trying to access a page that required a log in, this will let them go to that page after log in

    return render_template('static_site/login.html', form=form, error=error)

AtlasSwitch/templates/employee_site/advisory_board.html
{% extends 'employee_site/base.html' %}

{% block content %}
Advisory Board block
{% endblock %}

AtlasSwitch/templates/employee_site/all_quotes.html
{% extends 'employee_site/base.html' %}

{% block content %}
<div class='container' style='margin-top: 10px;'>
{% for quote in quotes.items %}

<div class='card' style='margin-top: 10px; margin-bottom: 10px;'>
    <h5 class='card-header'>{{ quote.id }}</h5>
    <div> Stuff </div>
</div>

{% endfor %}
</div>
{% endblock %}

AtlasSwitch/templates/employee_site/base.html
<!DOCTYPE html>
<html>
<head>
    <title> </title>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/mainpage.css')}}">
</head>
<body>

    <nav class='navbar navbar-expand-lg navbar-dark static-top navbar-fixed-top header-wrapper'>
        <div class='container'>
        <a class="navbar-brand" href="{{url_for('core.index')}}">Atlas Switch</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class='collapse navbar-collapse' id='navbarContent'>
            <ul class='navbar-nav ml-auto'>
                {% if current_user.access_level=='admin' or current_user.access_level == 'sales' %}
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle='dropdown' role='button' aria-haspopup="true" aria-expanded="false"">Sales</a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{{url_for('employees.sales')}}">Sales Home</a>
                      <a class="dropdown-item" href="{{url_for('employees.quote')}}">Quote</a>
                      <a class="dropdown-item" href="{{url_for('employees.crm')}}">CRM</a>
                    </div>
                  </li>
                {% endif %}
                {% if current_user.access_level=='admin' %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('admin.admin_index')}}">Admin</a>
                  </li>
                {% endif %}
                <li class="nav-item">
                      <a class="nav-link" href="{{url_for('users.logout')}}">Log out</a>
                </li>
            </ul>
      </div>
  </nav>

{% block content %}

{% endblock %}

</body>
</html>

AtlasSwitch/templates/employee_site/crm.html
{% extends 'employee_site/base.html' %}

{% block content %}
CRM BLock
{% endblock %}

AtlasSwitch/templates/employee_site/engineering.html
{% extends 'employee_site/base.html' %}

{% block content %}
engineering block
{% endblock %}

AtlasSwitch/templates/employee_site/index.html
{% extends 'employee_site/base.html' %}

{% block content %}
<div class='container'>
<div class='row'>

    {% if current_user.access_level=='admin' or current_user.access_level =='sales' %}
    <div class='col-sm-12 col-md-6 col-lg-4' style='margin-top: 15px;'/>
        <a href="{{url_for('employees.sales')}}" style='text-decoration: none; color: black;'>
            <div class='card' style='height: 12rem;'>
                <h5 class='card-header'>Sales</h5>
                <div class='card-body'>
                    <p class='card-text'>For all things sales</p>
                </div>
            </div>
        </a>
    </div>
    {% endif %}

    <div class='col-sm-12 col-md-6 col-lg-4' style='margin-top: 15px;'/>
        <a href="{{url_for('employees.advisory_board')}}" style='text-decoration: none; color: black;'>
            <div class='card' style='height: 12rem;'>
                <h5 class='card-header'>Advisory Board</h5>
                <div class='card-body'>
                    <p class='card-text'>For list of Advisory Board jobs and their status</p>
                </div>
            </div>
        </a>
    </div>
    {% if current_user.access_level=='admin' or current_user.access_level =='engineer' %}
    <div class='col-sm-12 col-md-6 col-lg-4' style='margin-top: 15px;'/>
        <a href="{{url_for('employees.engineering')}}" style='text-decoration: none; color: black;'>
            <div class='card' style='height: 12rem;'>
                <h5 class='card-header'>Engineering</h5>
                <div class='card-body'>
                    <p class='card-text'>For all things engineering</p>
                </div>
            </div>
        </a>
    </div>
    {% endif %}
</div>
</div>
{% endblock %}

AtlasSwitch/templates/employee_site/quote.html
{% extends 'employee_site/base.html' %}

{% block content %}
<div class='container'>
    <div class='row'>
        <div class='col-sm-12, col-md-6 col-lg-4 container mt-2'>
            <button class='btn' data-toggle='modal' data-target='#new_quote_modal' style='background: #801515; color: white; width: 100%; font-size: 1.5rem;'>
            New Quote
        </button>
        </div>
        <div class='col-sm-12, col-md-6 col-lg-4 container mt-2'>
          <a href="{{url_for('employees.all_quotes')}}" class='btn' style='background: #801515; color: white; width: 100%; font-size: 1.5rem;'>
            All Quotes
          </a>
        </div>
        <div class="modal" tabindex="-1" role="dialog" id='new_quote_modal'>
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">New Quote</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form method='POST'>
                {{newquote.hidden_tag()}}
                <div class='form-group'>
                    {{newquote.jobname(placeholder=newquote.jobname.label.text)}}
                </div>
                <div class='form-group'>
                    {{newquote.jobaddress(placeholder=newquote.jobaddress.label.text)}}
                </div>
                <div class='form-group'>

                    {{newquote.amount(placeholder=newquote.amount.label.text)}}
                </div>
                <div class='form-group'>
                    {{newquote.followdate()}}<br>
                    <label>{{newquote.followdate.label}}</label>
                </div>
                <div class='form-group'>
                    {{newquote.notes(rows=10, cols='50', placeholder=newquote.notes.label.text) |safe }}
                </div>
              </div>
              <div class="modal-footer">
                <div class='form-group'>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                  {{newquote.submit(class='btn btn-danger')}}
                </div>
              </div>
              </form>
            </div>
          </div>
        </div>    
    </div>
    <div style='background: grey; margin-top: 15px;'>
        Search for your quote goes here
   </div>
</div>
{% endblock %}

AtlasSwitch/templates/employee_site/sales.html
{% extends 'employee_site/base.html' %}

{% block content %}
<div class='container'>
   <div class='row'>
       <div class='col-sm-12 col-md-6 col-lg-4' style='margin-top: 15px;'/>
        <a href="{{url_for('employees.quote')}}" style='text-decoration: none; color: black;'>
            <div class='card' style='height: 12rem;'>
                <h5 class='card-header'>Quoting</h5>
                <div class='card-body'>
                    <p class='card-text'>Quoting tools</p>
                </div>
            </div>
        </a>
    </div>
       <div class='col-sm-12 col-md-6 col-lg-4' style='margin-top: 15px;'/>
        <a href="{{url_for('employees.crm')}}" style='text-decoration: none; color: black;'>
            <div class='card' style='height: 12rem;'>
                <h5 class='card-header'>CRM Tool</h5>
                <div class='card-body'>
                    <p class='card-text'>Customer Relationship Management Tool</p>
                </div>
            </div>
        </a>
    </div>
   </div> 
</div>
{% endblock %}